### PR TITLE
Fix build warnings, and add .travis.yml

### PR DESCRIPTION
**Pull request by sestrella**
**TODO**

- [x] Setup Travis
- [x] Setup stack
- [x] Fix build warnings

### CODE REVIEW

**Comment by sestrella** [comment]
@gazay would you mind taking a look please

**Comment by sestrella** [comment]
@gazay more than happy to be a collaborator. Thank you

**Comment by gazay** [comment]
Done :) now you can merge this PR by yourself if it's ready :) thank you for interest in this lib and for your help :)

**Comment by sestrella** [comment]
@gazay thank you very much!

**Pull request merged**
